# situational answers: Likert ranges, leaning/"depends" on dilemmas and DISC, and how they reach the AI
UID = "data/users/u_testuser000000000000000/"
p, errs = mkpage(b, 1280, 900, extra="window.__NO_SEED__=true;")
p.wait_for_timeout(800)
p.click(".rail [data-go=journey]"); p.wait_for_timeout(200)
p.click('.jr-index [data-id=ipip]'); p.wait_for_timeout(200)
p.click('[data-act=ipip][data-n="1"][data-v="3"]'); p.click('[data-act=ipipFlex][data-n="1"]'); p.wait_for_timeout(100)
p.click('[data-act=ipip][data-n="1"][data-v="5"]'); p.click('[data-act=ipip][data-n="1"][data-v="2"]'); p.wait_for_timeout(100)
p.fill('.lk-note', "친한 자리에선 매우 그렇다, 낯선 모임에선 아닌 편"); p.wait_for_timeout(100)
shot(p, "f01_ipip_range", False)
for n, v in [(2, 2), (3, 4), (4, 3)]:
    p.click(f'[data-act=ipip][data-n="{n}"][data-v="{v}"]')
print("ipip1:", p.evaluate("JSON.stringify(document.querySelectorAll('.lk')[0].querySelectorAll('.opts .on,.opts .in').length)"))
p.wait_for_timeout(1300)
core = lambda: p.evaluate("JSON.stringify((w=>({a:w.ipip.answers['1'],note:(w.ipip.notes||{})['1']}))(window.__store.get('" + UID + "a_core')))")
print("stored:", core())
# finish the chapter to see the band
for k in range(1, 5):
    p.click("[data-act=stepNext]"); p.wait_for_timeout(80)
    for n in range(k * 4 + 1, k * 4 + 5): p.click(f'[data-act=ipip][data-n="{n}"][data-v="3"]')
p.click("[data-act=stepNext]"); p.wait_for_timeout(200)
print("band:", p.evaluate("!!document.querySelector('.track .band')"), p.evaluate("(document.querySelector('.trait .rng')||{}).textContent"))
shot(p, "f02_ipip_result", False)
# dilemma: leaning, depends (no auto-advance + note), clearly
p.click('.jr-index [data-id=values]'); p.wait_for_timeout(200)
p.click('[data-act=dilemma][data-i="0"][data-v="a"][data-s="1"]'); p.wait_for_timeout(400)
p.click('[data-act=dilemma][data-i="1"][data-v="m"]'); p.wait_for_timeout(400)
print("stayed on 2 after depends:", p.evaluate("document.querySelector('.dl .sc').textContent"))
p.fill('.dl input', "안정적일 땐 도전, 불안할 땐 안정"); shot(p, "f03_dilemma", False)
p.click("[data-act=stepNext]"); p.wait_for_timeout(100)
p.click('[data-act=dilemma][data-i="2"][data-v="b"][data-s="2"]'); p.wait_for_timeout(400)
# DISC
p.click('.jr-index [data-id=energy]'); p.wait_for_timeout(200)
for _ in range(2):
    for aid in p.evaluate("Array.from(document.querySelectorAll('[data-act=act][data-v=n]')).map(b=>b.dataset.a)"): p.click(f'[data-act=act][data-a={aid}][data-v=n]')
    p.click("[data-act=stepNext]"); p.wait_for_timeout(80)
p.click("[data-act=stepNext]"); p.wait_for_timeout(80)
for q in ["wake", "peak", "sleep"]: p.click(f'[data-act=chrono][data-q={q}] >> nth=0')
p.click("[data-act=stepNext]"); p.wait_for_timeout(80)
p.click('[data-act=disc][data-i="0"][data-v="m"]'); p.wait_for_timeout(100)
p.fill('.pair5 input', "회의에선 결론부터, 친한 동료와는 분위기 맞춰")
p.click('[data-act=disc][data-i="1"][data-v="b"][data-s="1"]'); p.wait_for_timeout(100)
shot(p, "f04_disc", False)
p.wait_for_timeout(1300)
print("values:", p.evaluate("JSON.stringify((v=>[v.picks,v.str,v.notes])(window.__store.get('" + UID + "a_core').values))"))
print("disc:", p.evaluate("JSON.stringify((e=>[e.disc,e.discStr,e.discNotes])(window.__store.get('" + UID + "a_core').energy))"))
# the interview prompt carries the situational section
p.click(".rail [data-go=interview]"); p.wait_for_timeout(200); p.click("[data-act=ivStart]"); p.wait_for_timeout(1200)
prompt = p.evaluate("window.__SENT__[window.__SENT__.length-1].input[0].content")
i = prompt.find("[상황에 따라 달라지는 모습")
print("prompt section:", prompt[i:i+260].replace("\n", " | ") if i >= 0 else "MISSING")
print("prompt rule:", "한 점으로 해석하지 말고" in prompt)
p.click(".rail [data-go=export]"); p.wait_for_timeout(200)
t = p.evaluate("document.querySelector('#packText').value")
print("pack:", "### 상황에 따라 달라지는 모습" in t, "| 외향성 range:", "상황에 따라" in t.split("## 성향")[1][:300] if "## 성향" in t else False)
print([e for e in errs if "ERR_FAILED" not in e])
