# 1) viewer who is not the owner -> blank profile, journey from scratch
p, errs = mkpage(b, 1280, 900, extra="window.__NOT_OWNER__=true;")
p.wait_for_timeout(500)
shot(p, "e01_stranger_home", False)
p.click(".rail [data-go=journey]"); p.wait_for_timeout(200); shot(p, "e02_stranger_journey", False)
p.click(".rail [data-go=portrait]"); p.wait_for_timeout(200); shot(p, "e03_stranger_portrait", False)
p.click(".rail [data-go=gantt]"); p.wait_for_timeout(200); shot(p, "e04_stranger_gantt", False)
p.click(".rail [data-go=map]"); p.wait_for_timeout(1500); shot(p, "e05_stranger_map", False)
p.click(".rail [data-go=metrics]"); p.wait_for_timeout(300); shot(p, "e05b_stranger_metrics", False)
print("stranger", errs)
# 2) no claude runtime at all
p2, errs2 = mkpage(b, 1280, 900, extra="window.__NO_CLAUDE_CAPS__=true;")
p2.wait_for_timeout(500); shot(p2, "e06_nocaps_home", False)
p2.click(".rail [data-go=interview]"); p2.wait_for_timeout(200); shot(p2, "e07_nocaps_interview", False)
print("nocaps", errs2)
# 3) AI refused
p3, errs3 = mkpage(b, 1280, 900, extra="window.__AI_FAIL__='not_granted';")
p3.click(".rail [data-go=interview]"); p3.wait_for_timeout(200)
p3.click("[data-act=ivStart]"); p3.wait_for_timeout(1200); shot(p3, "e08_aifail", False)
p3.click(".rail [data-go=portrait]"); p3.wait_for_timeout(300); shot(p3, "e09_aifail_portrait", False)
print("aifail", errs3)
# 4) reload persistence
p4, errs4 = mkpage(b, 1280, 900)
p4.click(".rail [data-go=journey]"); p4.wait_for_timeout(200)
p4.click('.jr-index [data-id=ipip]'); p4.wait_for_timeout(200)
p4.click('[data-act=ipip][data-n="1"][data-v="5"]'); p4.wait_for_timeout(1500)
st = p4.evaluate("JSON.stringify(Array.from(window.__store.entries()))")
p4.context.add_init_script("window.__PRESTORE__=" + st + ";")
p4.evaluate("window.__store.size")
print("persist ipip1 =", p4.evaluate("JSON.parse(JSON.stringify(window.__store.get('data/users/u_testuser000000000000000/profile'))).ipip.answers['1']"))
