p, errs = mkpage(b, 390, 844)
shot(p, "m01_home")
p.click(".tabbar [data-go=journey]"); time.sleep(0.2); shot(p, "m02_journey")
p.click('.jr-index [data-id=wheel]'); time.sleep(0.2); shot(p, "m03_wheel", False)
p.click(".tabbar [data-go=interview]"); time.sleep(0.2); shot(p, "m04_interview", False)
p.evaluate("location.hash='#portrait'"); time.sleep(0.3); shot(p, "m05_portrait_empty")
p.click(".tabbar [data-go=ledger]"); time.sleep(0.2); shot(p, "m08_ledger", False)
p.click(".tabbar [data-go=export]"); time.sleep(0.2); shot(p, "m09_export", False)
p.evaluate("location.hash='#tree'"); time.sleep(0.3); shot(p, "m10_tree", False)
p.evaluate("location.hash='#gantt'"); time.sleep(0.3); shot(p, "m06_gantt", False)
p.evaluate("location.hash='#map'"); time.sleep(1.0); shot(p, "m07_map", False)
print("\n".join(errs[:20]))
p2, errs2 = mkpage(b, 1360, 900, dark=True)
shot(p2, "d01_home", False)
p2.click(".rail [data-go=journey]"); time.sleep(0.2)
p2.click('.jr-index [data-id=loves]'); time.sleep(0.2); shot(p2, "d02_loves", False)
p2.click(".rail [data-go=gantt]"); time.sleep(0.3); shot(p2, "d03_gantt", False)
p2.click(".rail [data-go=map]"); time.sleep(1.0); shot(p2, "d04_map", False)
p2.click(".rail [data-go=metrics]"); time.sleep(0.3); shot(p2, "d05_metrics", False)
print("\n".join(errs2[:20]))
